// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCityAirQuality = "city_air_quality"

// CityAirQuality mapped from table <city_air_quality>
type CityAirQuality struct {
	ID    int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	PmNum int32 `gorm:"column:pmNum" json:"pmNum"`
}

// TableName CityAirQuality's table name
func (*CityAirQuality) TableName() string {
	return TableNameCityAirQuality
}
