// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameCityPersonNum = "city_person_num"

// CityPersonNum mapped from table <city_person_num>
type CityPersonNum struct {
	ID          int32   `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Year        int32   `gorm:"column:year" json:"year"`
	Num         float32 `gorm:"column:num" json:"num"`
	Percenteges float32 `gorm:"column:percenteges" json:"percenteges"`
}

// TableName CityPersonNum's table name
func (*CityPersonNum) TableName() string {
	return TableNameCityPersonNum
}
