// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameProblem = "problem"

// Problem mapped from table <problem>
type Problem struct {
	ID   int32 `gorm:"column:id;primaryKey" json:"id"`
	Type int32 `gorm:"column:type;primaryKey" json:"type"`
	Num  int32 `gorm:"column:num" json:"num"`
	Year int32 `gorm:"column:year;primaryKey" json:"year"`
}

// TableName Problem's table name
func (*Problem) TableName() string {
	return TableNameProblem
}
