// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Username string `gorm:"column:username" json:"username"`
	Acount   string `gorm:"column:acount" json:"acount"`
	Password string `gorm:"column:password" json:"password"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
